// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DUAN1_QL_BANQUANAOContext))]
    [Migration("20240117182635_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Models.Chatlieu", b =>
                {
                    b.Property<string>("MaChatLieu")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaChatLieu")
                        .HasName("PK__CHATLIEU__453995BCE5B106D4");

                    b.ToTable("CHATLIEU", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Hoadon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HOADON__835ED13B8199D526");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("SoDienThoai");

                    b.ToTable("HOADON", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Hoadonchitiet", b =>
                {
                    b.Property<string>("MaHoaDonChiTiet")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaSanPhamChiTiet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDonChiTiet")
                        .HasName("PK__HOADONCH__6C2FD0CE8DB9FB9E");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSanPhamChiTiet");

                    b.ToTable("HOADONCHITIET", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Khachhang", b =>
                {
                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime");

                    b.HasKey("SoDienThoai")
                        .HasName("PK__KHACHHAN__0389B7BC50DA20DF");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Khuyenmai", b =>
                {
                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KieuKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MucGiam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaKhuyenMai")
                        .HasName("PK__KHUYENMA__6F56B3BD55C473B5");

                    b.ToTable("KHUYENMAI", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Kichthuoc", b =>
                {
                    b.Property<string>("MaKichThuoc")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaKichThuoc")
                        .HasName("PK__KICHTHUO__22BFD6640728F522");

                    b.ToTable("KICHTHUOC", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Mausac", b =>
                {
                    b.Property<string>("MaMauSac")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaMauSac")
                        .HasName("PK__MAUSAC__B9A91162318CD7E1");

                    b.ToTable("MAUSAC", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Nhanvien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NamSinh")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenNhanVien")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NHANVIEN__77B2CA47A8736C5A");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Salesanpham", b =>
                {
                    b.Property<string>("MaSale")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.HasKey("MaSale")
                        .HasName("PK__SALESANP__B234B7A71DA7C800");

                    b.ToTable("SALESANPHAM", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Sanpham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("GiaBan")
                        .HasColumnType("float");

                    b.Property<string>("MaThuongHieu")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SANPHAM__FAC7442D65F77FA7");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Sanphamchitiet", b =>
                {
                    b.Property<string>("MaSanPhamChiTiet")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("MaChatLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaKichThuoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaMauSac")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaSale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaSanPhamChiTiet")
                        .HasName("PK__SANPHAMC__0409209EAE7F1332");

                    b.HasIndex("MaChatLieu");

                    b.HasIndex("MaKichThuoc");

                    b.HasIndex("MaMauSac");

                    b.HasIndex("MaSale");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SANPHAMCHITIET", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Thuonghieu", b =>
                {
                    b.Property<string>("MaThuongHieu")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThuongHieu")
                        .HasName("PK__THUONGHI__A3733E2CA6329A27");

                    b.ToTable("THUONGHIEU", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Hoadon", b =>
                {
                    b.HasOne("DAL.Models.Khuyenmai", "MaKhuyenMaiNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaKhuyenMai")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MaKhuyen__49C3F6B7");

                    b.HasOne("DAL.Models.Nhanvien", "MaNhanVienNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaNhanVien")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__MaNhanVi__68487DD7");

                    b.HasOne("DAL.Models.Khachhang", "SoDienThoaiNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("SoDienThoai")
                        .IsRequired()
                        .HasConstraintName("FK__HOADON__SoDienTh__4BAC3F29");

                    b.Navigation("MaKhuyenMaiNavigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("SoDienThoaiNavigation");
                });

            modelBuilder.Entity("DAL.Models.Hoadonchitiet", b =>
                {
                    b.HasOne("DAL.Models.Hoadon", "MaHoaDonNavigation")
                        .WithMany("Hoadonchitiets")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__HOADONCHI__MaHoa__4CA06362");

                    b.HasOne("DAL.Models.Sanphamchitiet", "MaSanPhamChiTietNavigation")
                        .WithMany("Hoadonchitiets")
                        .HasForeignKey("MaSanPhamChiTiet")
                        .IsRequired()
                        .HasConstraintName("FK__HOADONCHI__MaSan__4D94879B");

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaSanPhamChiTietNavigation");
                });

            modelBuilder.Entity("DAL.Models.Sanpham", b =>
                {
                    b.HasOne("DAL.Models.Thuonghieu", "MaThuongHieuNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaThuongHieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAM__MaThuon__4E88ABD4");

                    b.Navigation("MaThuongHieuNavigation");
                });

            modelBuilder.Entity("DAL.Models.Sanphamchitiet", b =>
                {
                    b.HasOne("DAL.Models.Chatlieu", "MaChatLieuNavigation")
                        .WithMany("Sanphamchitiets")
                        .HasForeignKey("MaChatLieu")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaCha__4F7CD00D");

                    b.HasOne("DAL.Models.Kichthuoc", "MaKichThuocNavigation")
                        .WithMany("Sanphamchitiets")
                        .HasForeignKey("MaKichThuoc")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaKic__5070F446");

                    b.HasOne("DAL.Models.Mausac", "MaMauSacNavigation")
                        .WithMany("Sanphamchitiets")
                        .HasForeignKey("MaMauSac")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaMau__5165187F");

                    b.HasOne("DAL.Models.Salesanpham", "MaSaleNavigation")
                        .WithMany("Sanphamchitiets")
                        .HasForeignKey("MaSale")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaSal__52593CB8");

                    b.HasOne("DAL.Models.Sanpham", "MaSanPhamNavigation")
                        .WithMany("Sanphamchitiets")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__SANPHAMCH__MaSan__534D60F1");

                    b.Navigation("MaChatLieuNavigation");

                    b.Navigation("MaKichThuocNavigation");

                    b.Navigation("MaMauSacNavigation");

                    b.Navigation("MaSaleNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("DAL.Models.Chatlieu", b =>
                {
                    b.Navigation("Sanphamchitiets");
                });

            modelBuilder.Entity("DAL.Models.Hoadon", b =>
                {
                    b.Navigation("Hoadonchitiets");
                });

            modelBuilder.Entity("DAL.Models.Khachhang", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.Khuyenmai", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.Kichthuoc", b =>
                {
                    b.Navigation("Sanphamchitiets");
                });

            modelBuilder.Entity("DAL.Models.Mausac", b =>
                {
                    b.Navigation("Sanphamchitiets");
                });

            modelBuilder.Entity("DAL.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.Salesanpham", b =>
                {
                    b.Navigation("Sanphamchitiets");
                });

            modelBuilder.Entity("DAL.Models.Sanpham", b =>
                {
                    b.Navigation("Sanphamchitiets");
                });

            modelBuilder.Entity("DAL.Models.Sanphamchitiet", b =>
                {
                    b.Navigation("Hoadonchitiets");
                });

            modelBuilder.Entity("DAL.Models.Thuonghieu", b =>
                {
                    b.Navigation("Sanphams");
                });
#pragma warning restore 612, 618
        }
    }
}
